repos:
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
    -   id: ruff-format
    rev: v0.2.0
-   repo: local
    hooks:
    -   id: cargo-fmt
        name: cargo fmt
        types: [rust]
        language: rust
        entry: cargo fmt --
    -   id: check-version-num
        name: check that version numbers match
        entry: python check_version_numbers.py
        language: system
        pass_filenames: false
    -   id: codegen
        name: run code generation
        entry: python kuiper_documentation/codegen.py
        language: system
        pass_filenames: false
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-builtin-literals
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer
