repos:
-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        args: [--config=kuiper_python/pyproject.toml]
-   repo: local
    hooks:
    -   id: cargo-fmt
        name: cargo fmt
        types: [rust]
        language: rust
        entry: cargo fmt --
    -   id: check-version-num
        name: check that version numbers match
        entry: python check_version_numbers.py
        language: system
        pass_filenames: false
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-builtin-literals
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: end-of-file-fixer
