[project]
name = "cognite-kuiper"
version = "0.3.0"
description = "A JSON to JSON transform and templating language from Cognite"
readme = "README.md"
requires-python = ">=3.10"
keywords = ["JSON", "transformation"]
authors = [
  {name = "Mathias Lohne", email = "mathias.lohne@cognite.com"}
]
maintainers = [
  {name = "Mathias Lohne", email = "mathias.lohne@cognite.com"}
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Rust",
  "Programming Language :: Python"
]

dependencies = [
]

[project.optional-dependencies]
test = [
  "pytest >=7,<8",
]

[package.metadata.maturin]
python-source = "python"

[project.urls]
homepage = "https://cognite.com"
repository = "https://github.com/cognitedata/kuiper"

[tool.black]
line-length = 120
target_version = ['py310']
include = '\.pyi?$'

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"
