[package]
name = "kuiper_lang"
version = "0.6.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
completions = []

[dependencies]
chrono = "0.4.33"
itertools = "0.12.0"
lazy_static = "1.4.0"
logos = "0.13"
once_cell = "1.19.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.111"
regex = "1.10.3"
kuiper_lang_macros = { path = "../kuiper_lang_macros" }
lalrpop-util = "0.20.0"
thiserror = "1.0.56"

[dev-dependencies]
pprof = { version = "0.13", features = ["flamegraph"] }
criterion = "0.5"

[build-dependencies]
lalrpop = "0.20.0"

[[bench]]
name = "bench_execute"
harness = false
