[package]
name = "kuiper_lang"
version = "0.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
itertools = "0.11.0"
lazy_static = "1.4.0"
logos = "0.13"
once_cell = "1.18.0"
serde = { version = "1.0.176", features = ["derive"] }
regex = "1.9.1"
serde_json = "1.0.104"
kuiper_lang_macros = { path = "../kuiper_lang_macros" }
lalrpop-util = "0.20.0"
thiserror = "1.0.44"

[dev-dependencies]
pprof = { version = "0.12", features = ["flamegraph"] }
criterion = "0.5"

[build-dependencies]
lalrpop = "0.20.0"

[[bench]]
name = "bench_execute"
harness = false
