[package]
name = "kuiper_lang"
version = "0.9.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
completions = []

[dependencies]
chrono = "0.4.38"
itertools = "0.12.1"
lazy_static = "1.4.0"
logos = "0.14"
once_cell = "1.19.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.115"
regex = "1.10.4"
kuiper_lang_macros = { path = "../kuiper_lang_macros" }
lalrpop-util = "0.20.2"
thiserror = "1.0.59"

[dev-dependencies]
pprof = { version = "0.13", features = ["flamegraph"] }
criterion = "0.5"

[build-dependencies]
lalrpop = "0.20.2"

[[bench]]
name = "bench_execute"
harness = false
