[package]
name = "kuiper-cli"
version = "0.7.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.113"
kuiper_lang = { path = "../kuiper_lang" }
clap = { version = "4.4.18", features = ["derive"] }
rustyline = { version = "13.0.0", features = ["derive"] }
colored = "2.1.0"
dirs = "5.0.1"
