[package]
name = "kuiper-cli"
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.108"
kuiper_lang = { path = "../kuiper_lang" }
clap = { version = "4.4.7", features = ["derive"] }
rustyline = { version = "12.0.0", features = ["derive"] }
colored = "2.0.4"
dirs = "5.0.1"
