[package]
name = "kuiper-cli"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.104"
kuiper_lang = { path = "../kuiper_lang" }
clap = { version = "4.3.22", features = ["derive"] }
rustyline = { version = "12.0.0", features = ["derive"] }
dirs = "5.0.1"
