[package]
name = "kuiper_lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
tower-lsp = "0.20.0"
regex = "1.10.4"

kuiper_lang = { path = "../kuiper_lang" }