[package]
name = "kuiper_lang_macros"
version = "0.6.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc_macro = true

[dependencies]
syn = { version = "2.0.40", features=["full", "derive", "parsing", "printing", "clone-impls", "proc-macro"] }
quote = { version = "1.0.33" }
proc-macro2 = { version = "1.0.70" }
