name: Build and test library

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  common:
    uses: ./.github/workflows/common.yml
    secrets: inherit
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Run clippy
        run: cargo clippy -- -D warnings
      - name: Run cargo format
        run: cargo fmt --check

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Test
        run: cargo llvm-cov --workspace --exclude kuiper_cli --codecov --output-path codecov.json --locked

      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v5
        with:
          files: codecov.json
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: cognitedata/kuiper

      - name: Test interop library
        run: kuiper_interop/test/compile_and_run.sh

  build_python_bindings:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1
        with:
          toolchain: stable
          components: rustfmt
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dev deps and build package
        working-directory: kuiper_python
        run: |
          pip install uv pre-commit toml pyyaml
          uv sync
      - name: Check style
        run: pre-commit run --all
      - name: Check that docs are up to date
        run: |
          python kuiper_documentation/codegen.py
          git diff --quiet
      - name: Run tests
        working-directory: kuiper_python
        run: uv run pytest

  build_js_modules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Set Node.js 18.x
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version: 18.x

      # WASM module
      - name: Setup wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build wasm package
        working-directory: ./kuiper_js
        run: wasm-pack build --weak-refs --scope cognite

      # Codemirror module
      - name: Run install
        working-directory: ./kuiper_lezer
        run: yarn install --frozen-lockfile
      - name: Run test
        working-directory: ./kuiper_lezer
        run: yarn prepare && yarn test

  build_and_test_dotnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup .NET
        uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5
        with:
            dotnet-version: 8.0.x
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1
        with:
          toolchain: stable
      - name: Build interop lib
        run: cargo build --release --package kuiper_interop
      - name: Test .NET
        run: dotnet test /p:BuildLocalOnly='true'
