name: Release

on:
  push:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Run clippy
        run: cargo clippy -- -D warnings
      - name: Run cargo format
        run: cargo fmt --check
      - name: Test
        run: cargo test

  publish_python_bindings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - uses: PyO3/maturin-action@v1
        with:
          command: build
          working-directory: ./kuiper_python
          args: --release
      - name: Install twine
        run: pip install twine
      - name: Publish artifact
        env:
          TWINE_USERNAME: ${{ secrets.ARTIFACTORY_PUBLISH_TOKEN_USER }}
          TWINE_PASSWORD: ${{ secrets.ARTIFACTORY_PUBLISH_TOKEN }}
          TWINE_REPOSITORY_URL: https://cognite.jfrog.io/cognite/api/pypi/snakepit
        run: twine upload ./target/wheels/*
