name: Release

on:
  push:
    branches: [main]

jobs:
  build_ubuntu_python_bindings:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ubuntu-latest
    environment: CD
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1
        with:
          toolchain: stable
      - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3
      - uses: PyO3/maturin-action@86b9d133d34bc1b40018696f782949dac11bd380 # v1
        with:
          command: build
          working-directory: ./kuiper_python
          args: --release -i python${{ matrix.python-version }}
          manylinux: auto
      - name: Upload wheels
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: wheels-linux-${{ matrix.python-version }}
          path: ./target/wheels

  build_python_bindings_darwin:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        arch: ["x86_64-apple-darwin", "aarch64-apple-darwin"]
    runs-on: macos-latest
    environment: CD
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1
        with:
          toolchain: stable
      - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6
        with:
          python-version: ${{ matrix.python-version }}
      - uses: PyO3/maturin-action@86b9d133d34bc1b40018696f782949dac11bd380 # v1
        with:
          command: build
          working-directory: ./kuiper_python
          args: --release -i python${{ matrix.python-version }} --target ${{ matrix.arch }}
          manylinux: auto
      - name: Upload wheels
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: wheels-mac-${{ matrix.arch }}-${{ matrix.python-version }}
          path: ./target/wheels

  build_python_bindings_windows:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1
        with:
          toolchain: stable
      - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build wheels
        uses: PyO3/maturin-action@86b9d133d34bc1b40018696f782949dac11bd380 # v1
        with:
          command: build
          working-directory: ./kuiper_python
          args: --release -i python${{ matrix.python-version }}
      - name: Upload wheels
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: wheels-win-${{ matrix.python-version }}
          path: ./target/wheels

  publish_python_bindings:
    runs-on: ubuntu-latest
    environment: CD
    needs: ["build_python_bindings_darwin", "build_ubuntu_python_bindings", "build_python_bindings_windows"]
    steps:
      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7
        with:
          pattern: wheels-*
          merge-multiple: true
          path: ./wheels
      - name: Install twine
        run: pip install twine typing-extensions
      - name: Publish artifact
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload --verbose wheels/* || echo 'Version exists'

  publish_codemirror_module:
    runs-on: ubuntu-latest
    environment: CD
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Set Node.js 18.x
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          node-version: 18.x
      - name: Authenticate with npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc

      # WASM module
      - name: Setup wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build wasm package
        working-directory: ./kuiper_js
        run: wasm-pack build --weak-refs --scope cognite
      - name: Copy npmrc to package dir
        run: cp .npmrc ./kuiper_js/pkg/.npmrc
      - name: Publish wasm package
        working-directory: ./kuiper_js/pkg
        run: npm publish || true

      # Codemirror module
      - name: Run install
        working-directory: ./kuiper_lezer
        run: yarn install --frozen-lockfile
      - name: Build package
        working-directory: ./kuiper_lezer
        run: yarn prepare
      - name: Publish package
        working-directory: ./kuiper_lezer
        run: npm publish || true

  build_interop_package:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: macos-latest
            arch: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1
        with:
          toolchain: stable
      - name: Build interop lib
        run: cargo build --release --package kuiper_interop
      - run: mkdir artifacts
      - run: mv target/release/*kuiper_interop* artifacts/
      - name: Upload artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: interop-${{ matrix.os }}
          path: artifacts/
          retention-days: 1

  publish_dotnet_package:
    runs-on: windows-latest
    needs: build_interop_package
    environment: CD
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Setup .NET
        uses: actions/setup-dotnet@2016bd2012dba4e32de620c46fe006a3ac9f0602 # v5
        with:
            dotnet-version: 8.0.x
      - name: Download Linux Artifacts
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7
        with:
            name: interop-ubuntu-latest
            path: binaries/linux_x64/

      - name: Download Windows Artifacts
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7
        with:
            name: interop-windows-latest
            path: binaries/windows_x64/

      - name: Download OSX arm64 Artifacts
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7
        with:
            name: interop-macos-latest
            path: binaries/osx_arm64/
      - run: ls binaries/
      - name: Build .NET module
        run: dotnet pack KuiperNet/ /p:BuildLocalOnly='false' --output nuget-packages
      - name: Sign nuget packages
        env:
          CERTIFICATE_HOST: ${{ secrets.CODE_SIGNING_CERT_HOST }}
          CERTIFICATE_HOST_API_KEY: ${{ secrets.CODE_SIGNING_CERT_HOST_API_KEY }}
          CERTIFICATE_FINGERPRINT: ${{ secrets.CODE_SIGNING_CERT_SHA256_HASH }}
          CLIENT_CERTIFICATE: ${{ secrets.CODE_SIGNING_CLIENT_CERT }}
          CLIENT_CERTIFICATE_PASSWORD: ${{ secrets.CODE_SIGNING_CLIENT_CERT_PASSWORD }}
          KEYPAIR_ALIAS: ${{ secrets.CODE_SIGNING_KEYPAIR_ALIAS }}
        uses: cognitedata/code-sign-action/@a29458b69495966f90920f07aeed5acfe03e1f45 # v5
        with:
          path-to-binary: 'nuget-packages/'
      - name: Publish .NET module
        run: dotnet nuget push .\nuget-packages\*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate
        continue-on-error: false
