name: Release

on:
  push:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Run clippy
        run: cargo clippy -- -D warnings
      - name: Run cargo format
        run: cargo fmt --check
      - name: Test
        run: cargo test

  publish_python_bindings:
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - uses: PyO3/maturin-action@v1
        with:
          command: build
          working-directory: ./kuiper_python
          args: --release -i python${{ matrix.python-version }}
          manylinux: auto
      - name: Install twine
        run: pip install twine
      - name: Publish artifact
        env:
          TWINE_USERNAME: ${{ secrets.ARTIFACTORY_PUBLISH_TOKEN_USER }}
          TWINE_PASSWORD: ${{ secrets.ARTIFACTORY_PUBLISH_TOKEN }}
          TWINE_REPOSITORY_URL: https://cognite.jfrog.io/cognite/api/pypi/snakepit
        run: twine upload ./target/wheels/* || true

  build_python_bindings_darwin:
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        arch: ["x86_64-apple-darwin", "aarch64-apple-darwin"]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dev deps
        run: pip install pre-commit toml
      - name: Check style
        run: pre-commit run --all
      - uses: PyO3/maturin-action@v1
        with:
          command: build
          working-directory: ./kuiper_python
          args: --release -i python${{ matrix.python-version }} --target ${{ matrix.arch }}
          manylinux: auto
      - name: Install twine
        run: pip install twine
      - name: Publish artifact
        env:
          TWINE_USERNAME: ${{ secrets.ARTIFACTORY_PUBLISH_TOKEN_USER }}
          TWINE_PASSWORD: ${{ secrets.ARTIFACTORY_PUBLISH_TOKEN }}
          TWINE_REPOSITORY_URL: https://cognite.jfrog.io/cognite/api/pypi/snakepit
        run: twine upload ./target/wheels/* || true

  publish_codemirror_module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Authenticate with npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc

      # WASM module
      - name: Setup wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build wasm package
        working-directory: ./kuiper_js
        run: wasm-pack build --weak-refs --scope cognite
      - name: Copy npmrc to package dir
        run: cp .npmrc ./kuiper_js/pkg/.npmrc
      - name: Publish wasm package
        working-directory: ./kuiper_js/pkg
        run: npm publish

      # Codemirror module
      - name: Run install
        working-directory: ./kuiper_lezer
        run: yarn install --frozen-lockfile
      - name: Build package
        working-directory: ./kuiper_lezer
        run: yarn prepare
      - name: Publish package
        working-directory: ./kuiper_lezer
        run: npm publish
