name: Release

on:
  push:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Run clippy
        run: cargo clippy -- -D warnings
      - name: Run cargo format
        run: cargo fmt --check
      - name: Test
        run: cargo test

  publish_python_bindings:
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - uses: PyO3/maturin-action@v1
        with:
          command: build
          working-directory: ./kuiper_python
          args: --release -i python${{ matrix.python-version }}
          manylinux: auto
      - name: Install twine
        run: pip install twine
      - name: Publish artifact
        env:
          TWINE_USERNAME: ${{ secrets.ARTIFACTORY_PUBLISH_TOKEN_USER }}
          TWINE_PASSWORD: ${{ secrets.ARTIFACTORY_PUBLISH_TOKEN }}
          TWINE_REPOSITORY_URL: https://cognite.jfrog.io/cognite/api/pypi/snakepit
        run: twine upload ./target/wheels/* || true

  publish_codemirror_module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Run install
        working-directory: ./kuiper_lezer
        run: yarn install --frozen-lockfile
      - name: Authenticate with npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
      - name: Publish package
        working-directory: ./kuiper_lezer
        run: npm publish
